{
 "title": "Fritzmon",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Verbindungsstatus",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gateway_wan_connection_status" }
   ]
  },
  {
   "title": "Verbunden seit",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "gateway_wan_connection_uptime_seconds"
    }
   ]
  },
  {
   "title": "Bandbreitennutzung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(gateway_wan_bytes_sent[5m])",
     "legendFormat": "Bytes Gesendet"
    },
    {
     "expr": "irate(gateway_wan_bytes_received[5m])*-1",
     "legendFormat": "Bytes Empfangen"
    }
   ]
  },
  {
   "title": "DSL Geschwindigkeit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(speedtest_bits_per_second{direction=\"downstream\"}[60m])*-1",
     "legendFormat": "downstream"
    },
    {
     "expr": "avg_over_time(speedtest_bits_per_second{direction=\"upstream\"}[60m])",
     "legendFormat": "upstream"
    }
   ]
  }
 ]
}